### ISSUE TITLE
端口监听哪个？

### ISSUE THREAD

**Issue by Jumbo-WJB** [brianwrf/NagaScan#1]
飞侠好，按照readme配置好了，但是有一步有点问题，最后那里sqlmap server端口配置的是哪个？是不是要运行sqlmapapi？最后浏览器是要代理哪个端口？谢谢了

**Comment by brianwrf** [comment]
是的，sqlmapapi的默认端口是8775， 浏览器的代理默认是8080

**Comment by brianwrf** [comment]
另外，readme里默认设置的代理的端口是443.

**Comment by Jumbo-WJB** [comment]
OK，搞的，谢了，close掉吧。
